version: '3.8'

#Docker Networks
networks:
  proxy:
    external:
      name: nginx-proxy

# Workflow
services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    # volumes:
    #   - ./src:/var/www/html:delegated
    container_name: ${COMPOSE_PROJECT_NAME}__nuxt
    restart: always
    ports:
      - "5001:5001"
    command:
      "npm run start"
    networks:
      - proxy